apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: SIGNING_SECRET
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: SIGNING_SECRET
             - name: CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: CLIENT_ID
             - name: CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: CLIENT_SECRET
             - name: SUCCESS_URL
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: SUCCESS_URL
             - name: RABBIT_MQ
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: RABBIT_MQ
             - name: DIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: DIRECT_URL
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: DATABASE_URL
             - name: SUCCESS_URL
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: SUCCESS_URL
             - name: CANCEL_URL
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: CANCEL_URL
             - name: STRIPE_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: payments-microservice-config-secret
                   key: STRIPE_SECRET_KEY
